name: DailyQuests
version: '${project.version}'
main: dev.valid.daily_quests.DailyQuests
api-version: '1.20'
commands:
  dailyquests:
  dq:
depend:
  - BeautyQuests
permissions:
  dq.bypass:
    default: op